# Site settings
email: 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Adrian Costa
email: info@adriancosta.com.ar
description: 
url: "http://www.adriancosta.com.ar"
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]


github_username:  adricos
repository: "adricos/adricos.github.io"