baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://www.adriancosta.com.ar" # the base hostname & protocol for your site
github_username:  adricos
repository: "adricos/adricos.github.io"
title: Adrian Costa
description: Personal site
email: info@adriancosta.com.ar

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

#contacts
git: "https://github.com/adricos"
facebook: "https://www.facebook.com/adrian.costa"
instagram: "https://www.instagram.com/adrian.esteban.costa"
linkedin: "https://www.linkedin.com/in/adriancosta"

#disqus comment
disqus:
    shortname: "adriancosta" #your disqus comment short name

#google analytics
google:
    tracking-id: "UA-2111905-1" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-video-embed

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
